# Generated by Django 3.1 on 2021-08-10 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ytapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='songs',
            name='singer',
            field=models.TextField(null=True),
        ),
    ]
