# Generated by Django 3.1 on 2021-08-10 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ytapi', '0002_auto_20210810_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='songs',
            name='singer',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
